### ISSUE TITLE
Chapter 1 error with Keras

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Neural-Network-Projects-with-Python#11]
Dear James,
I am following the book and I installed the environment as indicated. I am running on Mac OS X 11.2.3.
I get an error on Chapter 1 with Keras (see attached file for the full description of the terminal output).
[NNPP_chapter1_error.txt](https://github.com/PacktPublishing/Neural-Network-Projects-with-Python/files/6150587/NNPP_chapter1_error.txt)
Thanks for your help,
Best,
Stephane

**Comment by ghost** [comment]
Dear James,
Updating the environment somewhat fixed the issue. I get only a warning now:
2021-03-16 09:49:20.702262: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/stephane/miniconda3/envs/neural-network-projects-python/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

I probably need to install Tensorflow from the source.

**Comment by sonam-packt** [comment]
Hi @sboutet,

Thank you for the suggestion!
