### ISSUE TITLE
if point == 'pickup' isn't correct

### ISSUE THREAD

**Issue by eapfel** [PacktPublishing/Neural-Network-Projects-with-Python#5]
https://github.com/PacktPublishing/Neural-Network-Projects-with-Python/blob/4f521c399389db412d900a1337f9031b4874295b/Chapter03/visualize.py#L39

Always plot same graphics because you are using 'Pickup'

**Comment by deepesh-packt** [comment]
Hey, thanks for the feedback. I'll forward this to the author. 
Regards.
